### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#14]
If I were a new person, I would not know what a `.cfm` vs `.cfc` vs who knows what.

Maybe something about application.cfc being special would be good too.

**Comment by adamcameron** [comment]
Yup, this def needs a mention. Probably a mention in chapter 0 along the lines of if ppl want to use ColdFusion itself rather than commandbox, then they'll need to save the files, and the extension is cfm. Then in chapter 4 we're discussing components, so CFCs will come in then.

Thinking abut it now I might revise the commandbox stuff out of the mix as it only runs Lucee I think, and I want to shift this back to be ColdFusion centric (there's too many discrepancies between the two dialects, so I'm just gonna mostly ignore Lucee I think.

**Comment by jmohler1970** [comment]
Some of the screenshots look like `<cfdump>` from Railo or Lucee.

**Comment by adamcameron** [comment]
@jmohler1970 that comment has nothing to do with this issue. Did you mean to raise another issue? That said, I think I've updated all the dumps now anyhow?

**Comment by adamcameron** [comment]
.cfm as the baseline extension is covered here: https://github.com/adamcameron/cfml24h/blob/master/chapters/00-housekeeping.md#running-coldfusion-express

.cfc is mentioned in https://github.com/adamcameron/cfml24h/blob/master/chapters/04-components.md#class-component

Application.cfc has its own chapter https://github.com/adamcameron/cfml24h/blob/master/chapters/10-application_framework.md
