### ISSUE TITLE
CFML flavors

### ISSUE THREAD

**Issue by jmohler1970** [adamcameron/cfml24h#17]
Adobe ColdFusion, Railo, Lucee are BlueDragon are all out there. Developers need to be aware of the variations

**Comment by adamcameron** [comment]
I've changed the editorial positioning on this since I started. CFML is defined by Adobe. Variations that Lucee has (no-one cares about OpenBD and Railo is obsolete) is - IMO - an implementation/design bug in Lucee. There's mention of vendors in chapter 0, but that'll be it. That chapter does need revision to reflect the change in editorial position though.

**Comment by adamcameron** [comment]
I've covered this in chapter 0.
